apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: comeandeat
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid #Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: comeandeat
        spec:
          restartPolicy: OnFailure
          containers:
          - name: kubectl
            image: bitnami/kubectl 
            command:
            - kubectl
            - rollout
            - restart
            - deployment/comeandeat
 