# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comeandeat
spec:
  replicas: 1
  selector:
     matchLabels:
      app: comeandeat
  template:
    metadata:
      labels:
        app: comeandeat
    spec:
      containers:
      - name: comeandeatcontainer
        image: rodion31/comeandeat:latest
        # livenessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /tmp/healthy
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        ports:
        - containerPort: 80
        # env:
        #   - name: APP_NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: app-config-map
        #         key: APP_NAME
    


