# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 5
  selector:
    name: deployment
  template:
    containers:
      - name: container
        image: registry/conatiner:latest
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config-map
                key: APP_NAME

