# docker-compose.yml
version: "3"
services:
  # Server
  myapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: comeandeat
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - APP_PORT
      - APP_NAME
    volumes:
      - datavol:/Users/radi/DEV/data
    expose:
      - 8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
volumes:
  datavol: 
    name: ${VOLUME_DATA}
    external: true
    
    # name: jopa
    #   hostPath:
    #   # directory location on host
    #   path: /Users/radi/Dev/data
    #   # this field is optional
    #   type: Directory                

