# docker-compose.yml
version: "3"
services:
  # Server
  myapp:
    container_name: $CONTAINER_NAME
    build:
      context: $CUSTOM_IMAGE_FOLDER
      dockerfile: ./app/Dockerfile    
    ports:
      - "8080:8080"
    env_file:
      - .env
    # environment:
    #   - APP_PORT
    #   - APP_NAME
    # volumes:
      # - datavol:.
    expose:
      - 8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
# volumes:
#   datavol: 
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /Users/radi/Dev/data
   

    # name: jopa
    #   hostPath:
    #   # directory location on host
    #   path: /Users/radi/Dev/data
    #   # this field is optional
    #   type: Directory                

