apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Set the default namespace for all the resources
namespace: comeandeat

# The files to be processed
# Kustomization will re-order the kinds if required
resources:
- namespace.yaml
- configMap.yaml
- storage.yaml
- service.yaml
# - statefulSet.yaml
- deployment.yaml
# - cronJob.yaml

