apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Set the default namespace for all the resources
namespace: comeandeat_namespace

# The files to be processed
# Kustomization will re-order the kinds if required
resources:
  - ConfigMap.yaml
  - Storage.yaml
  - Service.yaml
  - StatefulSet.yaml
  - Images.yaml

# ex: main metdata, spec.metadata etc
configMapGenerator:
  # Generate config file from env file
  # Check the diffrence between the `files` option below
  - name: configMapFromEnv
    env: .env
  # Generate config file from input file
  - name: configFromFile
    files:
      - .env 

