apiVersion: v1
kind: Service
metadata:
  name: comeandeat
  labels:
    app: comeandeat
spec:
  selector:
    app: comeandeat
  # Service of type nodeport
  type: NodePort
  # The deafult port for postgres
  ports:
    - port: 5432
